services:
  deeplearning:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    stdin_open: true
