services:
  deeplearning:
    build:
      context: .
      dockerfile: ./config/Dockerfile2
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    stdin_open: true
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8000 --allow-root --no-browser
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
