services:
  deeplearning:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.kaggle:/root/.kaggle
    env_file:
      - ./config/.env
    stdin_open: true
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8000 --allow-root --no-browser
